[package]
name = 'ygg-miner'
version = '0.1.0'
edition = '2021'

[dependencies]
ed25519-dalek = { version = '2.0.0-pre.0', default-features = true, features = ['rand_core', 'asm'] }
rdrand = { version = '0.8.2' }

[profile.release]
opt-level = 3
strip = true
lto = 'fat'
